import { LegalPage, type LegalSection } from "../components/guest/LegalPage";

const sections: LegalSection[] = [
  { id: "overview", title: "1. Overview", paragraphs: ["This draft Privacy Policy explains how <span class='placeholder'>[LEGAL BUSINESS NAME]</span> collects, uses, and protects information when you use ReachPilot."] },
  { id: "information", title: "2. Information we collect", paragraphs: ["We may collect account details such as your name, username, email address, and authentication data. We may also process profile, content, analytics, client-workspace, and connected-platform information that you choose to provide.", "We collect technical information needed to operate the service, such as device, browser, log, and security event data."] },
  { id: "use", title: "3. How we use information", paragraphs: ["We use information to provide and secure ReachPilot, respond to support requests, personalize product experiences, improve reliability, prevent abuse, and communicate service updates.", "We do not sell your personal information. Define any analytics, advertising, or AI-provider use here before publishing: <span class='placeholder'>[DESCRIBE ANALYTICS AND AI PROVIDERS]</span>."] },
  { id: "sharing", title: "4. When we share information", paragraphs: ["We may share information with service providers that help us host, secure, analyze, communicate about, or process payments for ReachPilot. Providers currently include <span class='placeholder'>[LIST PROVIDERS]</span>. We may also disclose information where required by law or to protect rights and safety."] },
  { id: "retention", title: "5. Retention and security", paragraphs: ["We retain information for as long as needed to provide the service and meet legal, security, and operational needs. Specify the applicable periods here: <span class='placeholder'>[DATA-RETENTION PERIODS]</span>.", "We use reasonable administrative, technical, and organizational safeguards. No online service can guarantee absolute security."] },
  { id: "rights", title: "6. Your choices", paragraphs: ["Depending on your location, you may have rights to access, correct, delete, export, or restrict certain processing of your information. Contact <span class='placeholder'>[LEGAL/SUPPORT EMAIL]</span> to make a request."] },
  { id: "contact", title: "7. Contact", paragraphs: ["Privacy questions can be sent to <span class='placeholder'>[LEGAL/SUPPORT EMAIL]</span>. Business address: <span class='placeholder'>[BUSINESS ADDRESS]</span>. Governing privacy jurisdiction: <span class='placeholder'>[JURISDICTION]</span>."] },
];

export default function PrivacyPage() { return <LegalPage eyebrow="Legal / 02" title="Privacy Policy" intro="A transparent starting point for how ReachPilot handles information." sections={sections} />; }
